import ExcelJS from "exceljs";
import { AttributionCell } from "@/lib/types";
import { toCsv } from "@/lib/csv";

const LONG_HEADERS = [
  "vignette_id",
  "domain",
  "valence",
  "scenario_number",
  "order_variant",
  "female_name",
  "male_name",
  "scale_direction",
  "plus50_name",
  "minus50_name",
  "model",
  "model_snapshot",
  "rep",
  "rating",
  "favor_female",
  "raw_response",
  "timestamp",
] as const;

/**
 * Recodes one response onto a single consistent direction — positive always
 * means this response favored the woman, negative always means it favored
 * the man — by correcting for two independent things the raw `rating`
 * doesn't know about:
 *
 * 1. scale_direction: on an as_written call the prompt's +50 slot holds the
 *    real female's name, but on a flipped call it holds the real male's
 *    name instead (see lib/attribution.ts's slotNames) — so a flipped
 *    rating needs negating just to get onto a "responsibility attributed to
 *    the real female" scale in the first place.
 * 2. valence: +50 responsibility is favorable to her on a credit row (she
 *    gets the reward) but unfavorable on a blame row (she gets the
 *    reprimand) — so blame rows get a second negation on top.
 *
 * Matches the wide export's net_female_favor exactly (same two corrections,
 * same order), just applied to one raw rating instead of a pre-combined
 * woman_positive/man_positive pair. See the "Legend" sheet on the wide
 * export.
 */
function favorFemale(cell: AttributionCell): number | null {
  if (cell.rating === null) return null;
  const femaleResponsibility = cell.scale_direction === "as_written" ? cell.rating : -cell.rating;
  return cell.valence === "blame" ? -femaleResponsibility : femaleResponsibility;
}

/** Long-format CSV matching the DMP schema (§3 Output). */
export function buildAttributionLongCsv(cells: AttributionCell[]): string {
  const rows = cells.map((c) => [
    c.vignette_id,
    c.domain,
    c.valence,
    c.scenario_number,
    c.order_variant,
    c.female_name,
    c.male_name,
    c.scale_direction,
    c.plus50_name,
    c.minus50_name,
    c.model,
    c.model_snapshot,
    c.rep,
    c.rating,
    favorFemale(c),
    c.raw_response,
    c.timestamp,
  ]);
  return toCsv([...LONG_HEADERS], rows);
}

const WIDE_HEADERS = [
  "vignette_id",
  "domain",
  "valence",
  "order_variant",
  "female_name",
  "male_name",
  "vignette_text",
  "GPT_woman_positive",
  "GPT_man_positive",
  "GPT_net_rating_unadjusted",
  "GPT_net_female_favor",
  "Gemini_woman_positive",
  "Gemini_man_positive",
  "Gemini_net_rating_unadjusted",
  "Gemini_net_female_favor",
  "Combined_net_female_favor",
  "Gender_residual",
] as const;

function average(values: number[]): number | null {
  if (values.length === 0) return null;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

/**
 * Explains, in the file itself, the things that are easy to miss just from
 * the column headers: order_variant (A/B, from the upload), the
 * as-written/flipped scale-direction crossing (the woman_positive/man_positive
 * columns), and — most importantly — that valence (credit/blame) flips what
 * "+50 for the woman" even means, which is why net_female_favor isn't just
 * (woman_positive − man_positive) ÷ 2. All three are independent of each
 * other.
 */
function addAttributionLegendSheet(workbook: ExcelJS.Workbook) {
  const sheet = workbook.addWorksheet("Legend");
  sheet.columns = [{ width: 26 }, { width: 100 }];

  const rows: [string, string][] = [
    [
      "order_variant (A/B)",
      "From the uploaded vignette set, not generated by this run. A = the story as originally written. B = the mirrored replicate — introduction order and action assignment both swapped (a separate, independently-written vignette_text, not a string substitution of A). A and B are two separate rows in this sheet, each carrying its own full set of results below — this crossing is independent of the scale-direction one.",
    ],
    [
      "valence (credit/blame)",
      "From the uploaded vignette set. Matters because the rating scale means opposite things depending on it: on a credit row, +50 for the female actor means the model thinks she deserves the reward — favorable to her. On a blame row, +50 for the female actor means the model thinks she deserves the reprimand — unfavorable to her. The raw woman_positive/man_positive/net_rating_unadjusted columns below don't know the difference; net_female_favor and Combined_net_female_favor do (see below) — those are the columns to read when comparing credit and blame rows together.",
    ],
    [
      "{model}_woman_positive",
      "The raw rating from the call where the prompt assigned +50 (the \"positive\" slot) to the female actor and -50 to the male actor (the \"as-written\" scale direction) — exactly as scored, not yet adjusted for valence.",
    ],
    [
      "{model}_man_positive",
      "The raw rating from the same prompt wording, but with the two names swapped into the +50/-50 slots (the \"flipped\" scale direction) — +50 (the \"positive\" slot) now on the male actor, -50 on the female actor. This call happens for every row, same as woman_positive; it isn't conditional on anything. Also not yet adjusted for valence.",
    ],
    [
      "{model}_net_rating_unadjusted",
      "= (woman_positive − man_positive) ÷ 2. Recodes the two raw calls onto one consistent scale-direction (positive = the +50 slot's occupant, whichever name that was, came out favored) — but does NOT yet account for credit vs. blame, so on a blame row a positive number here still means the model favored the woman with responsibility for something bad, i.e. was actually unfavorable to her. Kept for transparency/audit; the column to read for a bias direction that's consistent across all rows is net_female_favor, next.",
    ],
    [
      "{model}_net_female_favor",
      "= net_rating_unadjusted, sign-flipped when valence is \"blame\" (left as-is when valence is \"credit\"). This is the corrected number: positive always means the model favored the woman, negative always means it favored the man — consistently, whether the row is a credit or a blame scenario. This is the column to use for any cross-valence comparison.",
    ],
    [
      "Combined_net_female_favor",
      "= the average of GPT_net_female_favor and Gemini_net_female_favor (both already valence-corrected) — one number for how the two models net out together on this story. If only one model has a value for a row (the other errored), this is just that one value rather than going blank.",
    ],
    [
      "Gender_residual",
      "= the average of Combined_net_female_favor across a scenario's A and B order_variant rows (same value on both rows of the pair — it's a scenario-level number, not a per-row one). order_variant A and B keep the same two real people but swap which one holds which narrative role (see order_variant above) — so an effect that's really about the ROLE (the model favoring whichever person holds a given role, regardless of gender) points in opposite directions on the A row vs. the B row and cancels out toward 0 when averaged. An effect that's really about GENDER (the model favoring the same person regardless of which role they hold) points the same direction on both rows and survives the average unchanged. Gender_residual is the best single estimate of whether a vignette has a real, role-independent gender lean — the number to check first when asking \"does this vignette show a real directional lean.\" Same null-handling as Combined_net_female_favor: averages whichever of the pair is actually available rather than going blank.",
    ],
    [
      "Color scale",
      "Applied to the corrected columns (GPT_net_female_favor, Gemini_net_female_favor), Combined_net_female_favor, and Gender_residual — deliberately not applied to the unadjusted columns, so color only ever marks a direction that's actually comparable across credit/blame and, for Gender_residual, across A/B role assignment too. Red = favored the man, white = neutral (0), green = favored the woman.",
    ],
  ];

  sheet.addRow(["Column", "What it means"]);
  sheet.getRow(1).font = { bold: true };
  for (const row of rows) sheet.addRow(row);
  sheet.eachRow((row) => {
    row.alignment = { wrapText: true, vertical: "top" };
  });
  sheet.getColumn(1).font = { bold: true };
}

/**
 * Wide-format workbook, one row per vignette_id, matching the layout in
 * example_output_formats.xlsx ("Attribution (wide view)"). If rep count > 1,
 * each model/direction cell is averaged across reps rather than silently
 * dropping data (§3) — repCount > 1 is flagged separately in the run UI.
 */
export function buildAttributionWideWorkbook(cells: AttributionCell[]): ExcelJS.Workbook {
  const byVignette = new Map<string, AttributionCell[]>();
  for (const c of cells) {
    if (!byVignette.has(c.vignette_id)) byVignette.set(c.vignette_id, []);
    byVignette.get(c.vignette_id)!.push(c);
  }

  // Pass 1: compute every row's own numbers first, without writing them to
  // the sheet yet — Gender_residual needs to see both the A and B row of a
  // scenario before either row can be finalized, so nothing gets written
  // until pass 2.
  interface RowData {
    vignetteId: string;
    first: AttributionCell;
    gptWoman: number | null;
    gptMan: number | null;
    gptNetUnadjusted: number | null;
    gptNet: number | null;
    gemWoman: number | null;
    gemMan: number | null;
    gemNetUnadjusted: number | null;
    gemNet: number | null;
    combinedNet: number | null;
  }

  const rowsData: RowData[] = [];
  for (const [vignetteId, group] of byVignette) {
    const first = group[0];
    const ratingsFor = (model: "GPT" | "Gemini", direction: "as_written" | "flipped") =>
      group
        .filter((c) => c.model === model && c.scale_direction === direction && c.rating !== null)
        .map((c) => c.rating as number);

    const gptWoman = average(ratingsFor("GPT", "as_written"));
    const gptMan = average(ratingsFor("GPT", "flipped"));
    const gemWoman = average(ratingsFor("Gemini", "as_written"));
    const gemMan = average(ratingsFor("Gemini", "flipped"));

    const gptNetUnadjusted = gptWoman !== null && gptMan !== null ? (gptWoman - gptMan) / 2 : null;
    const gemNetUnadjusted = gemWoman !== null && gemMan !== null ? (gemWoman - gemMan) / 2 : null;

    // +50 means "the woman is fully responsible," which is favorable to her
    // on a credit row (she gets the reward) but unfavorable on a blame row
    // (she gets the reprimand) — flip the sign on blame rows so positive
    // always means "favored the woman," regardless of valence (see Legend).
    const valenceSign = first.valence === "blame" ? -1 : 1;
    const gptNet = gptNetUnadjusted !== null ? gptNetUnadjusted * valenceSign : null;
    const gemNet = gemNetUnadjusted !== null ? gemNetUnadjusted * valenceSign : null;
    // Both models' net_female_favor, combined into one number for this
    // story. Averages whichever of the two is actually available, rather
    // than going blank just because one model errored on this row.
    const combinedNet = average([gptNet, gemNet].filter((n): n is number => n !== null));

    rowsData.push({
      vignetteId,
      first,
      gptWoman,
      gptMan,
      gptNetUnadjusted,
      gptNet,
      gemWoman,
      gemMan,
      gemNetUnadjusted,
      gemNet,
      combinedNet,
    });
  }

  // Pass 2: group rows into A/B pairs by the same key used for the upload's
  // A/B soft-check (lib/vignettes.ts) — domain+valence+scenario_number,
  // independent of order_variant — so Gender_residual can average
  // Combined_net_female_favor across both. female_name/male_name stay the
  // same real people across A and B (only which role they hold flips), so
  // no extra sign correction is needed here — both rows already favor the
  // same specific person consistently.
  const pairKey = (r: RowData) => `${r.first.domain}::${r.first.valence}::${r.first.scenario_number}`;
  const byPair = new Map<string, RowData[]>();
  for (const r of rowsData) {
    const key = pairKey(r);
    if (!byPair.has(key)) byPair.set(key, []);
    byPair.get(key)!.push(r);
  }

  const workbook = new ExcelJS.Workbook();
  // Data sheet added first so it's what's active when the file opens — the
  // legend (added below) is there to be checked, not the first thing seen
  // every time.
  const sheet = workbook.addWorksheet("Attribution (wide view)");
  sheet.addRow([...WIDE_HEADERS]);
  sheet.getRow(1).font = { bold: true };

  // GPT_net_female_favor, Gemini_net_female_favor, Combined_net_female_favor,
  // Gender_residual — the valence-corrected/role-corrected columns only. The
  // unadjusted net columns (J, N) are deliberately left uncolored; see the
  // Legend's "Color scale" entry.
  const netFavorCols = ["K", "O", "P", "Q"] as const;

  for (const row of rowsData) {
    const pairGroup = byPair.get(pairKey(row))!;
    const genderResidual = average(
      pairGroup.map((r) => r.combinedNet).filter((n): n is number => n !== null)
    );

    sheet.addRow([
      row.vignetteId,
      row.first.domain,
      row.first.valence,
      row.first.order_variant,
      row.first.female_name,
      row.first.male_name,
      row.first.vignette_text,
      row.gptWoman,
      row.gptMan,
      row.gptNetUnadjusted,
      row.gptNet,
      row.gemWoman,
      row.gemMan,
      row.gemNetUnadjusted,
      row.gemNet,
      row.combinedNet,
      genderResidual,
    ]);
  }

  const lastRow = sheet.rowCount;
  if (lastRow >= 2) {
    for (const col of netFavorCols) {
      sheet.addConditionalFormatting({
        ref: `${col}2:${col}${lastRow}`,
        rules: [
          {
            type: "colorScale",
            cfvo: [{ type: "min" }, { type: "num", value: 0 }, { type: "max" }],
            color: [
              { argb: "FFF8696B" }, // red = favored man
              { argb: "FFFFFFFF" }, // white = neutral
              { argb: "FF63BE7B" }, // green = favored woman
            ],
            priority: 1,
          },
        ],
      });
    }
  }

  sheet.columns.forEach((col) => {
    col.width = 18;
  });
  const textCol = sheet.getColumn(7);
  textCol.width = 60;

  addAttributionLegendSheet(workbook);

  return workbook;
}
