import ExcelJS from "exceljs";
import { AttributionCell } from "@/lib/types";
import { toCsv } from "@/lib/csv";

const LONG_HEADERS = [
  "vignette_id",
  "domain",
  "valence",
  "scenario_number",
  "order_variant",
  "female_name",
  "male_name",
  "scale_direction",
  "plus50_name",
  "minus50_name",
  "model",
  "model_snapshot",
  "rep",
  "rating",
  "raw_response",
  "timestamp",
] as const;

/** Long-format CSV matching the DMP schema (§3 Output). */
export function buildAttributionLongCsv(cells: AttributionCell[]): string {
  const rows = cells.map((c) => [
    c.vignette_id,
    c.domain,
    c.valence,
    c.scenario_number,
    c.order_variant,
    c.female_name,
    c.male_name,
    c.scale_direction,
    c.plus50_name,
    c.minus50_name,
    c.model,
    c.model_snapshot,
    c.rep,
    c.rating,
    c.raw_response,
    c.timestamp,
  ]);
  return toCsv([...LONG_HEADERS], rows);
}

const WIDE_HEADERS = [
  "vignette_id",
  "domain",
  "valence",
  "order_variant",
  "female_name",
  "male_name",
  "vignette_text",
  "GPT_woman_first",
  "GPT_man_first",
  "GPT_net_female_favor",
  "Gemini_woman_first",
  "Gemini_man_first",
  "Gemini_net_female_favor",
  "Combined_net_female_favor",
] as const;

function average(values: number[]): number | null {
  if (values.length === 0) return null;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

/**
 * Explains, in the file itself, the two things that are easy to miss just
 * from the column headers: order_variant (A/B, from the upload) and the
 * as-written/flipped scale-direction crossing (the woman_first/man_first
 * columns) — both are fully crossed and independent of each other.
 */
function addAttributionLegendSheet(workbook: ExcelJS.Workbook) {
  const sheet = workbook.addWorksheet("Legend");
  sheet.columns = [{ width: 26 }, { width: 100 }];

  const rows: [string, string][] = [
    [
      "order_variant (A/B)",
      "From the uploaded vignette set, not generated by this run. A = the story as originally written. B = the mirrored replicate — introduction order and action assignment both swapped (a separate, independently-written vignette_text, not a string substitution of A). A and B are two separate rows in this sheet, each carrying its own full set of results below — this crossing is independent of the scale-direction one.",
    ],
    [
      "{model}_woman_first",
      "The rating from the call where the prompt assigned +50 to the female actor and -50 to the male actor (the \"as-written\" scale direction). Positive = the model favored the woman in that call; negative = favored the man.",
    ],
    [
      "{model}_man_first",
      "The rating from the same prompt wording, but with the two names swapped into the +50/-50 slots (the \"flipped\" scale direction) — +50 now on the male actor, -50 on the female actor. This call happens for every row, same as woman_first; it isn't conditional on anything.",
    ],
    [
      "{model}_net_female_favor",
      "= (woman_first − man_first) ÷ 2. Recodes both calls onto one consistent scale: positive always means the model favored the woman, negative always means it favored the man — regardless of which raw column the number came from. It also doubles as a consistency check: if the model isn't affected by which name sits in the +50 slot, woman_first and -man_first should be close to each other.",
    ],
    [
      "Combined_net_female_favor",
      "= the average of GPT_net_female_favor and Gemini_net_female_favor — one number for how the two models net out together on this story. If only one model has a value for a row (the other errored), this is just that one value rather than going blank.",
    ],
    [
      "Color scale",
      "Applied to all three net_female_favor columns (GPT, Gemini, and Combined): red = favored the man, white = neutral (0), green = favored the woman. Reading direction and strength doesn't require checking any numbers.",
    ],
  ];

  sheet.addRow(["Column", "What it means"]);
  sheet.getRow(1).font = { bold: true };
  for (const row of rows) sheet.addRow(row);
  sheet.eachRow((row) => {
    row.alignment = { wrapText: true, vertical: "top" };
  });
  sheet.getColumn(1).font = { bold: true };
}

/**
 * Wide-format workbook, one row per vignette_id, matching the layout in
 * example_output_formats.xlsx ("Attribution (wide view)"). If rep count > 1,
 * each model/direction cell is averaged across reps rather than silently
 * dropping data (§3) — repCount > 1 is flagged separately in the run UI.
 */
export function buildAttributionWideWorkbook(cells: AttributionCell[]): ExcelJS.Workbook {
  const byVignette = new Map<string, AttributionCell[]>();
  for (const c of cells) {
    if (!byVignette.has(c.vignette_id)) byVignette.set(c.vignette_id, []);
    byVignette.get(c.vignette_id)!.push(c);
  }

  const workbook = new ExcelJS.Workbook();
  // Data sheet added first so it's what's active when the file opens — the
  // legend (added below) is there to be checked, not the first thing seen
  // every time.
  const sheet = workbook.addWorksheet("Attribution (wide view)");
  sheet.addRow([...WIDE_HEADERS]);
  sheet.getRow(1).font = { bold: true };

  // GPT_net_female_favor, Gemini_net_female_favor, Combined_net_female_favor
  const netFavorCols = ["J", "M", "N"] as const;

  for (const [vignetteId, group] of byVignette) {
    const first = group[0];
    const ratingsFor = (model: "GPT" | "Gemini", direction: "as_written" | "flipped") =>
      group
        .filter((c) => c.model === model && c.scale_direction === direction && c.rating !== null)
        .map((c) => c.rating as number);

    const gptWoman = average(ratingsFor("GPT", "as_written"));
    const gptMan = average(ratingsFor("GPT", "flipped"));
    const gemWoman = average(ratingsFor("Gemini", "as_written"));
    const gemMan = average(ratingsFor("Gemini", "flipped"));

    const gptNet = gptWoman !== null && gptMan !== null ? (gptWoman - gptMan) / 2 : null;
    const gemNet = gemWoman !== null && gemMan !== null ? (gemWoman - gemMan) / 2 : null;
    // Both models' net_female_favor, combined into one number for this
    // story. Averages whichever of the two is actually available, rather
    // than going blank just because one model errored on this row.
    const combinedNet = average([gptNet, gemNet].filter((n): n is number => n !== null));

    sheet.addRow([
      vignetteId,
      first.domain,
      first.valence,
      first.order_variant,
      first.female_name,
      first.male_name,
      first.vignette_text,
      gptWoman,
      gptMan,
      gptNet,
      gemWoman,
      gemMan,
      gemNet,
      combinedNet,
    ]);
  }

  const lastRow = sheet.rowCount;
  if (lastRow >= 2) {
    for (const col of netFavorCols) {
      sheet.addConditionalFormatting({
        ref: `${col}2:${col}${lastRow}`,
        rules: [
          {
            type: "colorScale",
            cfvo: [{ type: "min" }, { type: "num", value: 0 }, { type: "max" }],
            color: [
              { argb: "FFF8696B" }, // red = favored man
              { argb: "FFFFFFFF" }, // white = neutral
              { argb: "FF63BE7B" }, // green = favored woman
            ],
            priority: 1,
          },
        ],
      });
    }
  }

  sheet.columns.forEach((col) => {
    col.width = 18;
  });
  const textCol = sheet.getColumn(7);
  textCol.width = 60;

  addAttributionLegendSheet(workbook);

  return workbook;
}
