import ExcelJS from "exceljs";
import { AttributionCell } from "@/lib/types";
import { toCsv } from "@/lib/csv";

const LONG_HEADERS = [
  "vignette_id",
  "domain",
  "valence",
  "scenario_number",
  "order_variant",
  "female_name",
  "male_name",
  "scale_direction",
  "plus50_name",
  "minus50_name",
  "model",
  "model_snapshot",
  "rep",
  "rating",
  "favor_female",
  "raw_response",
  "timestamp",
] as const;

/**
 * Recodes one response onto a single consistent direction — positive always
 * means this response favored the woman, negative always means it favored
 * the man — by correcting for two independent things the raw `rating`
 * doesn't know about:
 *
 * 1. scale_direction: on an as_written call the prompt's +50 slot holds the
 *    real female's name, but on a flipped call it holds the real male's
 *    name instead (see lib/attribution.ts's slotNames) — so a flipped
 *    rating needs negating just to get onto a "responsibility attributed to
 *    the real female" scale in the first place.
 * 2. valence: +50 responsibility is favorable to her on a credit row (she
 *    gets the reward) but unfavorable on a blame row (she gets the
 *    reprimand) — so blame rows get a second negation on top.
 *
 * Matches the wide export's net_female_favor exactly (same two corrections,
 * same order), just applied to one raw rating instead of a pre-combined
 * woman_positive/man_positive pair. See the "Legend" sheet on the wide
 * export.
 */
function favorFemale(cell: AttributionCell): number | null {
  if (cell.rating === null) return null;
  const femaleResponsibility = cell.scale_direction === "as_written" ? cell.rating : -cell.rating;
  return cell.valence === "blame" ? -femaleResponsibility : femaleResponsibility;
}

/** Long-format CSV matching the DMP schema (§3 Output). */
export function buildAttributionLongCsv(cells: AttributionCell[]): string {
  const rows = cells.map((c) => [
    c.vignette_id,
    c.domain,
    c.valence,
    c.scenario_number,
    c.order_variant,
    c.female_name,
    c.male_name,
    c.scale_direction,
    c.plus50_name,
    c.minus50_name,
    c.model,
    c.model_snapshot,
    c.rep,
    c.rating,
    favorFemale(c),
    c.raw_response,
    c.timestamp,
  ]);
  return toCsv([...LONG_HEADERS], rows);
}

const WIDE_HEADERS = [
  "vignette_id",
  "domain",
  "valence",
  "order_variant",
  "female_name",
  "male_name",
  "vignette_text",
  "GPT_woman_positive",
  "GPT_woman_positive_diff",
  "GPT_man_positive",
  "GPT_man_positive_diff",
  "GPT_average",
  "Gemini_woman_positive",
  "Gemini_woman_positive_diff",
  "Gemini_man_positive",
  "Gemini_man_positive_diff",
  "Gemini_average",
  "Combined_average",
] as const;

function average(values: number[]): number | null {
  if (values.length === 0) return null;
  return values.reduce((a, b) => a + b, 0) / values.length;
}

/**
 * Explains, in the file itself, the things that are easy to miss just from
 * the column headers: order_variant (A/B, from the upload), the
 * as-written/flipped scale-direction crossing (the woman_positive/man_positive
 * columns), and that every _diff/_average column below is a scenario-level
 * number — the same value duplicated on both the A row and the B row of a
 * pair, not something computed independently per row.
 */
function addAttributionLegendSheet(workbook: ExcelJS.Workbook) {
  const sheet = workbook.addWorksheet("Legend");
  sheet.columns = [{ width: 26 }, { width: 100 }];

  const rows: [string, string][] = [
    [
      "order_variant (A/B)",
      "From the uploaded vignette set, not generated by this run. A = the story as originally written. B = the mirrored replicate — introduction order and action assignment both swapped (a separate, independently-written vignette_text, not a string substitution of A). A and B are two separate rows in this sheet, each carrying its own full set of results below — this crossing is independent of the scale-direction one.",
    ],
    [
      "valence (credit/blame)",
      "From the uploaded vignette set. On a credit row, +50 for the female actor means the model thinks she deserves the reward. On a blame row, +50 means she deserves the reprimand. Not corrected for anywhere on this sheet — read alongside the numbers, not around them.",
    ],
    [
      "{model}_woman_positive",
      "The raw rating from the call where the prompt assigned +50 (the \"positive\" slot) to the female actor and -50 to the male actor (the \"as-written\" scale direction).",
    ],
    [
      "{model}_woman_positive_diff",
      "= {model}_woman_positive on the A row minus the same on the B row — a fixed A-minus-B calculation, so the same value is written on both rows of the pair, not something computed relative to \"this\" row. How differently the model rated the female actor depending on which narrative role she held.",
    ],
    [
      "{model}_man_positive",
      "The raw rating from the same prompt wording, but with the two names swapped into the +50/-50 slots (the \"flipped\" scale direction) — +50 (the \"positive\" slot) now on the male actor, -50 on the female actor. This call happens for every row, same as woman_positive; it isn't conditional on anything.",
    ],
    [
      "{model}_man_positive_diff",
      "= -1 × ({model}_man_positive on the A row minus the same on the B row) — already sign-flipped (unlike woman_positive_diff) so it lands on the same \"Role1 rating minus Role2 rating\" scale as woman_positive_diff, regardless of which gender happened to hold which role. Same value on both rows of the pair.",
    ],
    [
      "{model}_average",
      "= AVERAGE({model}_woman_positive_diff, {model}_man_positive_diff). Estimates the pure ROLE effect for this model: if the model rates whoever holds a given role more or less responsible regardless of gender, both inputs point the same way and this stays large. If the effect is really about gender rather than role, the two inputs tend to cancel toward 0.",
    ],
    [
      "Combined_average",
      "= AVERAGE(GPT_average, Gemini_average) — the two models' role-effect estimates combined into one number. Large in magnitude → the vignette's two narrative roles get treated very differently regardless of gender. Near 0 → no strong role effect either way. Averages whichever of the two models is actually available rather than going blank if one errored.",
    ],
    [
      "Color scale",
      "Applied to GPT_average, Gemini_average, and Combined_average. Red = Role2 rated more responsible than Role1 (net), white = no role effect, green = Role1 rated more responsible than Role2 (net) — not a favor-the-woman/man direction, since these columns aren't gender- or valence-corrected.",
    ],
  ];

  sheet.addRow(["Column", "What it means"]);
  sheet.getRow(1).font = { bold: true };
  for (const row of rows) sheet.addRow(row);
  sheet.eachRow((row) => {
    row.alignment = { wrapText: true, vertical: "top" };
  });
  sheet.getColumn(1).font = { bold: true };
}

/**
 * Wide-format workbook, one row per vignette_id, matching the layout in
 * example_output_formats.xlsx ("Attribution (wide view)"). If rep count > 1,
 * each model/direction cell is averaged across reps rather than silently
 * dropping data (§3) — repCount > 1 is flagged separately in the run UI.
 */
export function buildAttributionWideWorkbook(cells: AttributionCell[]): ExcelJS.Workbook {
  const byVignette = new Map<string, AttributionCell[]>();
  for (const c of cells) {
    if (!byVignette.has(c.vignette_id)) byVignette.set(c.vignette_id, []);
    byVignette.get(c.vignette_id)!.push(c);
  }

  // Pass 1: compute every row's own raw numbers (woman_positive/man_positive
  // per model), without writing them to the sheet yet — the _diff/_average
  // columns need to see both the A and B row of a scenario before either row
  // can be finalized.
  interface RowData {
    vignetteId: string;
    first: AttributionCell;
    gptWoman: number | null;
    gptMan: number | null;
    gemWoman: number | null;
    gemMan: number | null;
  }

  const rowsData: RowData[] = [];
  for (const [vignetteId, group] of byVignette) {
    const first = group[0];
    const ratingsFor = (model: "GPT" | "Gemini", direction: "as_written" | "flipped") =>
      group
        .filter((c) => c.model === model && c.scale_direction === direction && c.rating !== null)
        .map((c) => c.rating as number);

    rowsData.push({
      vignetteId,
      first,
      gptWoman: average(ratingsFor("GPT", "as_written")),
      gptMan: average(ratingsFor("GPT", "flipped")),
      gemWoman: average(ratingsFor("Gemini", "as_written")),
      gemMan: average(ratingsFor("Gemini", "flipped")),
    });
  }

  // Pass 2: group rows into A/B pairs by the same key used for the upload's
  // A/B soft-check (lib/vignettes.ts) — domain+valence+scenario_number,
  // independent of order_variant.
  const pairKey = (r: RowData) => `${r.first.domain}::${r.first.valence}::${r.first.scenario_number}`;
  const byPair = new Map<string, RowData[]>();
  for (const r of rowsData) {
    const key = pairKey(r);
    if (!byPair.has(key)) byPair.set(key, []);
    byPair.get(key)!.push(r);
  }

  // Every _diff/_average value is a fixed "A row minus B row" calculation —
  // the same value gets written to both rows of a pair, never something
  // computed relative to "whichever row this is" (that would flip sign
  // depending on which row you're looking at, which isn't what the approved
  // design does — see the woman_positive_diff/man_positive_diff Legend
  // entries). So these are computed once per pair here, then looked up by
  // both rows below, rather than recomputed per row.
  interface PairAverages {
    gptWomanDiff: number | null;
    gptManDiff: number | null;
    gptAverage: number | null;
    gemWomanDiff: number | null;
    gemManDiff: number | null;
    gemAverage: number | null;
    combinedAverage: number | null;
  }
  const diff = (a: number | null | undefined, b: number | null | undefined) =>
    a !== null && a !== undefined && b !== null && b !== undefined ? a - b : null;

  const pairAveragesByKey = new Map<string, PairAverages>();
  for (const [key, group] of byPair) {
    const rowA = group.find((r) => r.first.order_variant === "A");
    const rowB = group.find((r) => r.first.order_variant === "B");

    const gptWomanDiff = diff(rowA?.gptWoman, rowB?.gptWoman);
    const gptManDiffRaw = diff(rowA?.gptMan, rowB?.gptMan);
    // man_positive_diff is pre-negated relative to woman_positive_diff so
    // both land on the same "Role1 rating minus Role2 rating" scale,
    // regardless of which gender happened to hold which role (see Legend).
    const gptManDiff = gptManDiffRaw !== null ? -1 * gptManDiffRaw : null;
    const gptAverage = average([gptWomanDiff, gptManDiff].filter((n): n is number => n !== null));

    const gemWomanDiff = diff(rowA?.gemWoman, rowB?.gemWoman);
    const gemManDiffRaw = diff(rowA?.gemMan, rowB?.gemMan);
    const gemManDiff = gemManDiffRaw !== null ? -1 * gemManDiffRaw : null;
    const gemAverage = average([gemWomanDiff, gemManDiff].filter((n): n is number => n !== null));

    // Averages whichever of the two models is actually available, rather
    // than going blank just because one model errored on this pair.
    const combinedAverage = average(
      [gptAverage, gemAverage].filter((n): n is number => n !== null)
    );

    pairAveragesByKey.set(key, {
      gptWomanDiff,
      gptManDiff,
      gptAverage,
      gemWomanDiff,
      gemManDiff,
      gemAverage,
      combinedAverage,
    });
  }

  const workbook = new ExcelJS.Workbook();
  // Data sheet added first so it's what's active when the file opens — the
  // legend (added below) is there to be checked, not the first thing seen
  // every time.
  const sheet = workbook.addWorksheet("Attribution (wide view)");
  sheet.addRow([...WIDE_HEADERS]);
  sheet.getRow(1).font = { bold: true, name: "Cambria" };

  // GPT_average, Gemini_average, Combined_average — the only columns that
  // are role-effect estimates on a consistent scale; see the Legend's
  // "Color scale" entry for why the raw/diff columns are left uncolored.
  const averageCols = ["L", "Q", "R"] as const;

  for (const row of rowsData) {
    const d = pairAveragesByKey.get(pairKey(row))!;
    const excelRow = sheet.addRow([
      row.vignetteId,
      row.first.domain,
      row.first.valence,
      row.first.order_variant,
      row.first.female_name,
      row.first.male_name,
      row.first.vignette_text,
      row.gptWoman,
      d.gptWomanDiff,
      row.gptMan,
      d.gptManDiff,
      d.gptAverage,
      row.gemWoman,
      d.gemWomanDiff,
      row.gemMan,
      d.gemManDiff,
      d.gemAverage,
      d.combinedAverage,
    ]);
    excelRow.font = { name: "Arial" };
  }

  const lastRow = sheet.rowCount;
  if (lastRow >= 2) {
    for (const col of averageCols) {
      sheet.addConditionalFormatting({
        ref: `${col}2:${col}${lastRow}`,
        rules: [
          {
            type: "colorScale",
            cfvo: [{ type: "min" }, { type: "num", value: 0 }, { type: "max" }],
            color: [
              { argb: "FFF8696B" }, // red = Role2 rated more responsible
              { argb: "FFFFFFFF" }, // white = no role effect
              { argb: "FF63BE7B" }, // green = Role1 rated more responsible
            ],
            priority: 1,
          },
        ],
      });
    }
  }

  sheet.columns.forEach((col) => {
    col.width = 18;
  });
  const textCol = sheet.getColumn(7);
  textCol.width = 60;

  addAttributionLegendSheet(workbook);

  return workbook;
}
